"""
Django settings for sovothinkresort project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pksv!t++q2&ouh@y*9h72zvflcgf3a$17_!(q)grh4pe@xw)0y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTH_USER_MODEL = 'joinervoters.User'

ALLOWED_HOSTS = ['sovothinkresort.com', 'localhost', '127.0.0.1']

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'joinervoters',
    'ckeditor',
    'ckeditor_uploader',
    'django_cleanup',
    'taggit',
    'vote',
    'django_crontab',
    'haystack',
    'channels',
    'snowpenguin.django.recaptcha2',
    'django_extensions',
]

# Channels
ASGI_APPLICATION = 'sovothinkresort.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('sovothinkresort.com', 6379)],
        },
    },
}

SITE_ID = 1

CRONJOBS = [
	(' * / 262800 * * * * ', 'sovothinkresort.cron.president_selection'),
	(' * / 131400 * * * * ', 'sovothinkresort.cron.group_leadership'),
	(' * / 110400 * * * * ', 'sovothinkresort.cron.delete_user_underposts'),
	(' * / 216000 * * * * ', 'sovothinkresort.cron.delege_select')
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'sovothinkresort.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'sovothinkresort.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'sovothinkresortdata',
        'HOST': '127.0.0.1',
        'PORT': '',
        'USER': 'potgresqlusr',
        'PASSWORD': 'potgresqlpsswrd',
        # 'OPTIONS': {'charset': 'utf8'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login'
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_USERNAME_MIN_LENGTH = 4
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5


####################################
    ##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = 'static/js/jquery-3.1.1.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_RESTRICT_BY_DATE = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'tr-TR'

TIME_ZONE = 'Europe/Istanbul'

DATE_TIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M']

USE_I18N = True

USE_L10N = True

USE_TZ = True


#Email ayarları
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.com.tr'
EMAIL_HOST_USER = 'xxx@yandex.com.tr' #my yandex username
EMAIL_HOST_PASSWORD = 'abc123456' #my yandex password
EMAIL_PORT = 465
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'sovothinkresort/static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_ROOT = os.path.join(BASE_DIR , 'media')
MEDIA_URL = '/media/'

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://127.0.0.1:8983/solr/haystacksovothinksearch',
        'ADMIN_URL': 'http://127.0.0.1:8983/solr/admin/cores',
    },
}

CELERY_BROKER_URL = 'amqp://127.0.0.1'

RECAPTCHA_PUBLIC_KEY = 'recaptturepublic'
RECAPTCHA_PRIVATE_KEY = 'recaptureprivate'


ACCOUNT_SIGNUP_FORM_CLASS = 'joinervoters.forms.ReSignUpForm'

GOOGLE_RECAPTCHA_SECRET_KEY = 'recapturesecret'
